services:
  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb  # add what you need
      - DEBUG=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"