/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: ['test-bg'],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb5a1",
        "surface-container": "#edeeef",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdbd1",
        "on-secondary-fixed-variant": "#354a53",
        "on-primary-fixed": "#002020",
        "secondary-fixed": "#cfe6f2",
        "secondary-fixed-dim": "#b4cad6",
        "on-tertiary-fixed-variant": "#6d382a",
        "on-secondary-container": "#526772",
        "surface-tint": "#1b6869",
        "primary-fixed-dim": "#8dd3d3",
        "error": "#ba1a1a",
        "tertiary": "#4e2013",
        "on-surface-variant": "#3f4945",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "inverse-on-surface": "#f0f1f2",
        "secondary": "#4c616c",
        "on-tertiary-fixed": "#370e04",
        "primary-fixed": "#a8efef",
        "inverse-primary": "#8dd3d3",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "inverse-surface": "#2e3132",
        "secondary-container": "#cfe6f2",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#071e27",
        "on-primary-fixed-variant": "#004f50",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "on-primary-container": "#77bcbd",
        "primary": "#003334",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "outline": "#707975",
        "outline-variant": "#bfc9c4",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "tertiary-container": "#693527",
        "surface-container-high": "#e7e8e9",
        "surface": "#f8f9fa",
        "on-tertiary-container": "#e89f8c",
        "error-container": "#ffdad6",
        "primary-container": "#004c4d"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}