apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: inventory
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: mydb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  NODE_ENV: production
