apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: app
          image: ashimsharma/restaurant-inventory-management-app:v1.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: temp-storage
              mountPath: /tmp
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: temp-storage
          emptyDir: {}
